os: linux
dist: focal

language: node_js
node_js:
  - "lts/*"

services:
  - docker

branches:
  only:
  - master

install:
- npm install

script:
- npm run deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  fqdn: julianxhokaxhiu.com
  on:
    branch: master
