sudo: required

language: node_js
node_js:
  - "lts/carbon"

services:
  - docker

branches:
  only:
  - master

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y fontforge openjdk-8-jre libbatik-java autoconf libtool pkg-config nasm build-essential

install:
- npm install

script:
- npm run deploy

deploy:
  local-dir: _dist/
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  fqdn: julianxhokaxhiu.com
  on:
    branch: master
  # See https://github.com/travis-ci/travis-ci/issues/9312
  edge:
    branch: v1.8.47
