sudo: required

language: node_js
node_js:
  - "node"

services:
  - docker

branches:
  only:
  - master

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y fontforge openjdk-8-jre libbatik-java
- npm install -g ttf2eot ttf2svg bower grunt-cli

script:
- git clone -b gh-pages --single-branch https://github.com/julianxhokaxhiu/julianxhokaxhiu.com.git _dest
- npm install
- bower install
- grunt build_deploy

deploy:
  local_dir: _dest/
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: julianxhokaxhiu.com
  on:
    branch: master