sudo: required

language: node_js
node_js:
  - "lts/erbium"

services:
  - docker

branches:
  only:
  - master

install:
- npm install

script:
- npm run deploy

deploy:
  local-dir: dist/
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  fqdn: julianxhokaxhiu.com
  on:
    branch: master
